sudo: required
dist: xenial
language: cpp
compiler: gcc

git:
  depth: 3

addons:
  apt:
    packages: &standard_packages
    - libfftw3-dev
    - libnetcdf-dev
    - libnetcdf-c++4-dev
    - netcdf-bin
    - hdf5-tools
    - python3
    - python3-h5py
    - python3-pip
    - python3-numpy
    - python3-scipy
    - libhdf5-mpi-dev
    - openmpi-bin
    - libopenmpi-dev
    - liblapack-dev
    - libparpack2-dev

cache:
  directories:
  - $HOME/local

matrix:
  fast_finish: true
  include:
  - env: &default_env
      - CONFIGURE_OPTIONS=""
      - SCRIPT_FLAGS='-uim'
      - PIP_PACKAGES='netcdf4==1.4.2'
      - LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH

before_install:
  ##################################################
  # Job specific setup
  ##################################################
  # The following eval is the way to force CC/CXX to desired values as travis forces values
  # for these in the pre-before_install stage, see https://docs.travis-ci.com/user/languages/cpp/#C11-C%2B%2B11-(and-Beyond)-and-Toolchain-Versioning
  - eval "${MATRIX_EVAL}"
  - echo "${CC} $(${CC} --version)"
  ##################################################
  # Install remaining python3 packages using pip
  ##################################################
  - source .pip_install_for_travis.sh ${PIP_PACKAGES}

script:
  # Configure, compile and run test_suite
  - "./.travis_script.sh ${SCRIPT_FLAGS}"
